name: Build Manager

on:
  push:
    branches: ["main", "experimental"]
    paths:
      - "**.rs"
  pull_request:
    branches: ["main", "experimental"]
    paths:
      - "**.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd manager && cargo build --verbose
